= Methods

We now describe the Expert Pursuit pipeline in detail: how we extract expert activations, apply SOMP to characterize expert function, rank experts by concept relevance, and intervene on selected experts to validate the decomposition.

== Expert Activation Extraction

We target OLMoE-1B-7B @muennighoff2024olmoe, an open-source MoE language model with $L = 16$ layers, $E = 64$ experts per layer, and top-$k = 8$ routing. The model is traced using the `nnsight` framework, which allows us to intercept intermediate activations during the forward pass without modifying the model architecture.

For each token $bold(x)_i$ processed by the model, we capture two quantities at each layer $l$:
+ The _expert indices_ $cal(T)_k (bold(x)_i) subset {1, dots, E}$: the set of $k$ experts selected by the router.
+ The _gated outputs_ $g_e (bold(x)_i) dot f_e (bold(x)_i) in RR^d$ for each $e in cal(T)_k (bold(x)_i)$: the expert's FFN output multiplied by its router weight.

We store only the gated outputs for tokens that were actually routed to each expert (sparse storage), since non-routed tokens contribute exactly zero. This significantly reduces memory requirements compared to storing a dense $[n_"tokens", d]$ matrix per expert.

The dataset consists of documents drawn from The Pile @gao2020pile, tokenized with the model's tokenizer. Documents are processed in batches, and for each document, we record the per-layer, per-expert gated outputs along with the routing metadata (indices and weights).

== Aggregation

Following the Head Pursuit approach @basile2025headpursuit, which averages attention head outputs across prompt tokens before applying SOMP, we aggregate expert gated outputs at the document level. For each expert $e$ at layer $l$ and document $j$, we compute the mean gated output over only the tokens routed to that expert (see @eq:expert-agg).

If expert $e$ is never routed any tokens for document $j$ (i.e., $cal(R)_(e,l)^j = emptyset$), that document is excluded from the analysis of that expert. In practice, with top-8 routing and 64 experts, most experts are activated for a substantial fraction of tokens, so this case is rare for large documents.

== SOMP Application to Experts

Given the aggregated expert matrix $macron(bold(E))_(e,l) in RR^(n times d)$ for expert $e$ at layer $l$, we apply SOMP using the model's unembedding matrix $bold(D) in RR^(v times d)$ as the dictionary. The algorithm proceeds as described in the background (equations @eq:somp-approx through @eq:somp-refit), iteratively selecting vocabulary tokens whose corresponding unembedding vectors best explain the variance in the expert's aggregated output across documents.


- NOTE: This is to revise
*Perhaps here something lower would be reasonable considering the sparsity of experts, since each expert only processes $k\/E$ of tokens on average.*


After a fixed number of iterations $T$ (typically $T = 50$, following the Head Pursuit setting), the support set $SS^T$ contains the indices of the $T$ vocabulary tokens that form the sparse decomposition. These tokens provide a human-readable characterization of what the expert writes into the residual stream --- for instance, an expert whose SOMP decomposition is dominated by country names can be interpreted as specializing in geographic knowledge.

== Expert Ranking by Concept Specialization

Beyond characterizing individual experts with the full unembedding dictionary, we can target specific semantic concepts by restricting the dictionary to a subset of relevant tokens. Given a target concept $C$ defined by a set of vocabulary tokens (e.g., country names, color words, or sentiment-bearing terms), we construct a _concept-restricted dictionary_ $bold(D)_C in RR^(|C| times d)$ by selecting the corresponding rows from $bold(D)$.

We then apply SOMP to each expert's aggregated matrix $macron(bold(E))_(e,l)$ using $bold(D)_C$ as the dictionary, and compute the _fraction of variance explained_ by the SOMP reconstruction:

$ rho_(e,l)^C = 1 - frac(norm(macron(bold(E))_(e,l) - macron(bold(E))_(e,l)^("recon"))_F^2, norm(macron(bold(E))_(e,l))_F^2) $ <eq:variance-explained>

This ratio $rho_(e,l)^C in [0, 1]$ measures how well the expert's output can be approximated using only directions from the target concept. Experts with high $rho_(e,l)^C$ are considered _specialized_ for concept $C$. Ranking all experts across all layers by $rho_(e,l)^C$ yields a prioritized list of concept-relevant experts.

This approach mirrors the Head Pursuit strategy for identifying concept-specific attention heads, but applied to the expert setting. Importantly, the concept token lists can be obtained in various ways: manually curated lists, class label names, or keywords generated by an external LLM.

== Intervention Protocol

To validate that the identified experts genuinely mediate the target concept, we propose an intervention protocol analogous to that of Head Pursuit @basile2025headpursuit. During the forward pass, we rescale the gated output of selected experts by a coefficient $alpha$:

$ tilde(bold(E))_(e,l) [i] = alpha dot g_e (bold(x)_i) dot f_e (bold(x)_i) $ <eq:intervention>

Two intervention modes are of interest:
- *Suppression* ($alpha = -1$): inverting the sign of the expert's contribution, which disrupts its information flow into the residual stream. This tests whether the expert is necessary for generating concept-related tokens.
- *Enhancement* ($alpha > 1$): amplifying the expert's contribution, which should promote the generation of concept-related content if the expert is genuinely specialized.

As in Head Pursuit, this intervention affects not only the direct contribution of the expert at layer $l$, but also its indirect influence on all subsequent layers that read from the residual stream.

To ensure specificity, we include a _random control_ condition: intervening on a randomly selected set of experts that matches the targeted set in both size and layer distribution but is disjoint from the concept-relevant experts. Performance degradation under targeted intervention, combined with minimal effect under random control, provides evidence that the identified experts are genuinely specialized rather than merely important for general model function.
